### ISSUE TITLE
Linking the node version to the version specified in the Kibana?

### ISSUE THREAD

**Issue by milutz** [rigon/docker-kibana-dev#1]
Hi!

I just found your docker kibana dev image, looks very nice!

It looks like your always `FROM`ing the image from `node` (which I would interpret as `node:latest`.   The Kibana releases have a file in them specifying the node release they are to be built off of `.node-version`.

I pulled your 5.6.5 docker image and got:
```
# cat .node-version
6.11.5
```
but node reported its version as
```
# node -v
v9.3.0
```

While I doubt there is an easy way to automate this, do you expect you might ever match your `FROM` node version to the version specified in `.node-version`?

**Comment by rigon** [comment]
Hi! Thanks for your comment.

I have been working in the feature you proposed and it is finished now, finally!!
- I created the script `build.sh` that automates this process.
- I also built this image for older releases of Kibana, since version 3. But, right now, I do not have time and interest to test if all versions are actually working, I hope so :P
- Plus, I added two flavors of the image: `slim` (contains the minimal packages needed to run node) and `alpine` (based on the Alpine Linux).

Please, send me some feedback :D

**Comment by milutz** [comment]
Hi @rigon !

Your new builds are looking really good!

When I posted my last message, I needed a solution right away, so I've been building up my own at https://github.com/samtecspg/kibana-plugin-build

When I get some more free time I'll see if your new work will let me drop some of mine (and feel free to grab any ideas out of my system that seem helpful to you) - hopefully we'll find a way we can combine effort :)

**Comment by rigon** [comment]
Thank you!
Sorry, build the image took some time to manage all those versions and failed builds in DockerHub.

It will be really great if we can join efforts!
I'm closing this issue for now, let me updated ;)
